# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings
title:               'æŸšæœ¨ Youmoo'
description:         'Solid as teak. ğŸªµ'
author:              'Youmoo'
