# Minimalist settings for Youmoo

disqus:
  comments: false

google-ID: ''

menu: []

social:
- {icon: 'github',     link: 'https://github.com/bitteak/youmoo'}

pagination:
  next_page: 'Next'
  previous_page: 'Prev'

sharing_button_prompt: 'Share'
related_posts: 'Related:'
post_date_prefix: 'Date:'
